//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SieuThiSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANGCAO
    {
        public int STT { get; set; }
        public string TenCTy { get; set; }
        public string HinhMinhHoa { get; set; }
        public string HREF { get; set; }
        public Nullable<System.DateTime> Ngaybatdau { get; set; }
        public Nullable<System.DateTime> Ngayhethan { get; set; }
    }
}
