//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SieuThiSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMGIA
    {
        public int Masach { get; set; }
        public int MaTG { get; set; }
        public string Vaitro { get; set; }
    
        public virtual TACGIA TACGIA { get; set; }
    }
}
